### ISSUE TITLE
failed to find unique service of type 'rocon_interaction_msgs/SetInteractions' while concert start-up

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_tools#22]
Something has been changed.......

> roslaunch turtle_concert concert.launch  

with hydro-devel branch

```
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/rocon/src/rocon_concert/concert_service_manager/scripts/service_manager", line 22, in <module>
    sm = ServiceManager()
  File "/home/jihoonl/research/ros/rocon/src/rocon_concert/concert_service_manager/src/concert_service_manager/service_manager.py", line 50, in __init__
    self._interactions_loader = rocon_interactions.InteractionsLoader()
  File "/home/jihoonl/research/ros/rocon/src/rocon_tools/rocon_interactions/src/rocon_interactions/loader.py", line 44, in __init__
    % str(e))
rocon_python_comms.exceptions.NotFoundException: failed to find unique service of type 'rocon_interaction_msgs/SetInteractions' [ros shutdown]
```

**Comment by stonier** [comment]
Re the problem, nothing has changed around these functions. These issues are about timeouts in the find_xxx calls. Where are you receiving these errors? PC or turtlebot?

The gateway one is understandable, the default timeout was 1.0. This one though, is 15.0, which should be easily enough time.

**Comment by jihoonl** [comment]
It was my desktop. This is awkward. I have rebooted computer, the problem disappeared....anyway the problem is gone. closing the issue.

**Comment by stonier** [comment]
I updated the gateway lookup timeout for the hatchling in https://github.com/robotics-in-concert/concert_services/commit/7762cfef3ba9ab5d49931e7a156ee46e40a0efa2.
