### ISSUE TITLE
RemoconStatus property problem

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_tools#35]
It has no property of `running_app`

```
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 618, in _handle_request
    response = convert_return_to_response(self.handler(request), self.response_class)
  File "/home/dwlee/rocon/src/rocon_tools/rocon_interactions/src/rocon_interactions/manager.py", line 275, in _ros_service_request_interaction
    if remocon_monitor.status is not None and remocon_monitor.status.running_app:
AttributeError: 'RemoconStatus' object has no attribute 'running_app'
[ERROR] [WallTime: 1398818500.754596] Error processing request: 'RemoconStatus' object has no attribute 'running_app'
None
```

**Comment by stonier** [comment]
Should be fixed with the latest sync.

**Comment by stonier** [comment]
Oops, was a real bug.

**Comment by stonier** [comment]
Thanks @dwlee.
