### ISSUE TITLE
Cannot catch change of app_manager namespace

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_tools#57]
Rapp manager changes its handle's namespace when it sees gateway. 

rocon_interaction cannot react on this namespace change.

```
[INFO] [WallTime: 1405501875.293436]  - ~start_rapp
[INFO] [WallTime: 1405501875.301337] Rapp Manager : initialised.
[INFO] [WallTime: 1405501875.307359]  - /turtlebot6d08138483ab4836b68af71124703620/start_rapp
[ERROR] [WallTime: 1405501875.427936] Interactions : timed out trying to find the rapp manager status topic [multiple topics found ['/turtlebot6d08138483ab4836b68af71124703620/status', '/app_manager/status'].]
Traceback (most recent call last):
  File "/home/jihoonl/research/ros/turtlebot/src/rocon_tools/rocon_interactions/scripts/interactions_manager.py", line 20, in <module>
    interactions_manager = rocon_interactions.InteractionsManager()
  File "/home/jihoonl/research/ros/turtlebot/src/rocon_tools/rocon_interactions/src/rocon_interactions/manager.py", line 74, in __init__
    self._rapp_handler = RappHandler(self._rapp_manager_status_update_callback)
  File "/home/jihoonl/research/ros/turtlebot/src/rocon_tools/rocon_interactions/src/rocon_interactions/rapp_handler.py", line 74, in __init__
    thread = threading.Thread(target=self._setup_rapp_manager_connections())
  File "/home/jihoonl/research/ros/turtlebot/src/rocon_tools/rocon_interactions/src/rocon_interactions/rapp_handler.py", line 93, in _setup_rapp_manager_connections
    self.status_subscriber = rospy.Subscriber(status_topic_name, rocon_app_manager_msgs.Status, self._ros_status_subscriber)
UnboundLocalError: local variable 'status_topic_name' referenced before assignment
[interactions-13] process has died [pid 9301, exit code 1, cmd /home/jihoonl/research/ros/turtlebot/src/rocon_tools/rocon_interactions/scripts/interactions_manager.py __name:=interactions __log:=/home/jihoonl/.ros/log/0ab6a614-0cc9-11e4-a724-3085a9948f5e/interactions-13.log].
log file: /home/jihoonl/.ros/log/0ab6a614-0cc9-11e4-a724-3085a9948f5e/interactions-13*.log
```

**Comment by stonier** [comment]
Rapp manager no longer changes its namespace on the fly.
