### ISSUE TITLE
Crashing 'set' call

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_tools#74]
```
[INFO] [WallTime: 1421980723.387061] Rapp Manager : successfully flipped ['start_rapp', 'stop_rapp']
[INFO] [WallTime: 1421980723.387968] Rapp Manager : accepting invitation to be remote controlled [xavierdd0a64147de8484e99a79ccd7b30aaca]
[INFO] [WallTime: 1421980723.663202] Gateway : sending flip request [xavierdd0a64147de8484e99a79ccd7b30aaca][service][/chopina42e89e2e170419080cb3b8b8336c2dd/stop_rapp][/app_manager]
[INFO] [WallTime: 1421980723.699154] Gateway : sending flip request [xavierdd0a64147de8484e99a79ccd7b30aaca][service][/chopina42e89e2e170419080cb3b8b8336c2dd/start_rapp][/app_manager]
[INFO] [WallTime: 1421983085.568877] Gateway : lost connection with hub, attempting to disconnect...
Traceback (most recent call last):
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/scripts/gateway.py", line 22, in <module>
    gateway.spin()
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_node.py", line 78, in spin
    self._gateway.spin()
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 78, in spin
    self.watcher_thread.start()
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/watcher_thread.py", line 74, in start
    self._gateway.update_network_information()
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway.py", line 388, in update_network_information
    self.hub_manager.publish_network_statistics(statistics)
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/hub_manager.py", line 286, in publish_network_statistics
    hub.publish_network_statistics(statistics)
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_hub.py", line 204, in publish_network_statistics
    self.update_named_gateway_latency_stats(self._unique_gateway_name, latency)
  File "/home/yujin/ros/vendingmachine/src/rocon_multimaster/rocon_gateway/src/rocon_gateway/gateway_hub.py", line 249, in update_named_gateway_latency_stats
    self._redis_server.set(mdev_latency_key, latency_stats[3])
  File "/home/yujin/ros/vendingmachine/src/rocon_tools/rocon_python_redis/src/rocon_python_redis/client.py", line 610, in set
    return self.execute_command('SET', name, value)
  File "/home/yujin/ros/vendingmachine/src/rocon_tools/rocon_python_redis/src/rocon_python_redis/client.py", line 346, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/yujin/ros/vendingmachine/src/rocon_tools/rocon_python_redis/src/rocon_python_redis/client.py", line 356, in parse_response
    response = connection.read_response()
  File "/home/yujin/ros/vendingmachine/src/rocon_tools/rocon_python_redis/src/rocon_python_redis/connection.py", line 305, in read_response
    response = self._parser.read_response()
  File "/home/yujin/ros/vendingmachine/src/rocon_tools/rocon_python_redis/src/rocon_python_redis/connection.py", line 102, in read_response
    response = self.read()
  File "/home/yujin/ros/vendingmachine/src/rocon_tools/rocon_python_redis/src/rocon_python_redis/connection.py", line 87, in read
    return self._fp.readline()[:-2]
AttributeError: 'NoneType' object has no attribute 'readline'

```

**Comment by stonier** [comment]
Closing, old and haven't seen for a long time. Reopen if necessary.
