### ISSUE TITLE
Update InteractionsUpdate  message

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_tools#94]
`InteractionsUpdate` message is not updated in https://github.com/robotics-in-concert/rocon_tools/pull/92

```
Traceback (most recent call last):
  File "/home/dwlee/work/rocon_ws/src/rocon_tools/rocon_interactions/scripts/interactions_manager.py", line 20, in <module>
    interactions_manager = rocon_interactions.InteractionsManager()
  File "/home/dwlee/work/rocon_ws/src/rocon_tools/rocon_interactions/src/rocon_interactions/manager.py", line 72, in __init__
    self._publishers = self._setup_publishers()  # important to come early, so we can publish is_pairing below
  File "/home/dwlee/work/rocon_ws/src/rocon_tools/rocon_interactions/src/rocon_interactions/manager.py", line 199, in _setup_publishers
    interaction_msgs.InteractionsUpdate,
AttributeError: 'module' object has no attribute 'InteractionsUpdate'

```

**Comment by jihoonl** [comment]
#92 has been reverted back with #95
