### ISSUE TITLE
Interactions rapp watcher does not close down gracefully

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_tools#99]
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/opt/gopher_concert/src/rocon_tools/rocon_interactions/src/rocon_interactions/rapp_watcher.py", line 244, in run
    list_rapps_service_names = rocon_python_comms.find_service('rocon_app_manager_msgs/GetRappList', timeout=rospy.rostime.Duration(60.0), unique=False)
  File "/opt/gopher_concert/src/rocon_tools/rocon_python_comms/src/rocon_python_comms/services.py", line 111, in find_service
    next_service_type = get_service_headers(service_name, service_uri).get('type', None)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosservice/__init__.py", line 124, in get_service_headers
    return rosgraph.network.read_ros_handshake_header(s, StringIO(), 2048)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
```

**Comment by stonier** [comment]
I fixed.
